from ParameterTuning.BasicMagicCNN import parameterize_BasicMagicNet
from ParameterTuning.HexCircleCNN import parameterize_HexCircleNet
from ParameterTuning.HexagdlyCNN import parameterize_HexagdlyNet
from ParameterTuning.Simple1dCNN import parameterize_Simple1dNet